### PR TITLE
Production version

### LINKED ISSUE #3: Run zkEVM `zkvm_prove_only` on Gevulot
The target task:  [zkvm_prove_only](https://github.com/0xEigenLabs/eigen-zkvm/blob/main/zkvm/src/lib.rs#L211)

The E2E sample:  [code](https://github.com/0xEigenLabs/eigen-zkvm/blob/main/zkvm/src/lib.rs#L339). 

The command: 

```
RUST_MIN_STACK=2073741821 RUST_LOG=debug nohup cargo test --release test_zkvm_lr_execute_then_prove -- --nocapture  &
```

### PR DESCRIPTION
**Pull request by gavin-ygy**
1. adding production images(prove/verify)
2. adding e2e test for production version.

fix #3

### CODE REVIEW

**Comment by gavin-ygy** [comment]
The EVM task  is ok

**Comment by gavin-ygy** [comment]
add evm task

**Comment by gavin-ygy** [comment]
reopen

**Comment by eigmax** [comment]
Gevulot CPU Benchmark for eigen-zkvm: 


12-core: the proving in Gevulot duration 1099.554982089s

16-core: the proving in Gevulot duration 1005.666662438s

20-core: the proving in Gevulot duration 1010.611240473s

24-core: the proving in Gevulot duration 971.785845058s

32-core: the proving in Gevulot duration 1007.726214652s

48-core: the proving in Gevulot duration 1115.283285853s

64-core: the proving in Gevulot duration 1196.905375843s

**Pull request merged**
